[workspace]
members = [
    "crates/chat_pm_commands",
    "crates/chat_pm_session",
    "crates/chat_pm_database",
    "crates/chat_pm_deepseek",
    "crates/chat_pm_sync",
    "src-tauri"
]
resolver = "2" # Tauri 2.x 需要 resolver = "2"

[workspace.lints.clippy]
dbg_macro = "warn"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
chat_pm_session = { path = "crates/chat_pm_session" }
chat_pm_database = { path = "crates/chat_pm_database" }
chat_pm_deepseek = { path = "crates/chat_pm_deepseek" }
chat_pm_commands = { path = "crates/chat_pm_commands" }
chat_pm_sync = { path = "crates/chat_pm_sync" }
chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "2", features = ["from", "into", "as_ref"] }
dotenvy = "0.15"
futures-lite = "2.6"
logforth = { version = "0.29", features = ["bridge-log", "layout-text"] }
tracing = { version = "0.1", features = ["log"] }
http = { version = "1" }
rusqlite = { version = "0.37", features = ["bundled", "uuid"] }
reqwest = { version = "0.13", features = ["json", "stream"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "2" }
tokio = { version = "1", features = [] }
uuid = { version = "1", features = ["serde", "v7", "v4"] }
