[workspace]
members = [
    "crates/chat_pm_commands", "crates/chat_pm_conversation",
    "crates/chat_pm_database",
    "crates/chat_pm_deepseek",
    "src-tauri"
]
resolver = "2" # Tauri 2.x 需要 resolver = "2"

[workspace.lints.clippy]
dbg_macro = "warn"

[workspace.dependencies]
anyhow = "1"
async-openai = { version = "0.38", features = ["_api"] }
chat_pm_deepseek = { path = "crates/chat_pm_deepseek" }
chat_pm_commands = { path = "crates/chat_pm_commands" }
futures-lite = "2.6"
http = { version = "1" }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2" }
tokio = { version = "1", features = [] }
