[package]
name = "chat_pm_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
chat_pm_session = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
iroh = { workspace = true }
iroh-docs = { workspace = true }
serde_json = { workspace = true }


[lints]
workspace = true
