[package]
name = "chat_pm_database"
version = "0.1.0"
edition = "2024"

[dependencies]
chat_pm_session = { workspace = true }
chat_pm_sync = { workspace = true }
chrono = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
